# Generated by Django 5.2.8 on 2025-12-19 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='blogarticle',
            name='blog_blogar_status_7993db_idx',
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='edit_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='Причина редактирования'),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Проверено модератором'),
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_articles', to=settings.AUTH_USER_MODEL, verbose_name='Последний редактор'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='edit_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество правок'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время редактирования'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='is_highlighted',
            field=models.BooleanField(default=False, verbose_name='Выделенный комментарий'),
        ),
        migrations.AddIndex(
            model_name='blogarticle',
            index=models.Index(fields=['status', 'is_featured', 'published_at'], name='blog_blogar_status_639a41_idx'),
        ),
        migrations.AddIndex(
            model_name='blogarticle',
            index=models.Index(fields=['slug', 'status'], name='blog_blogar_slug_d5dbb1_idx'),
        ),
    ]
