# Generated by Django 5.2.8 on 2025-12-19 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogarticle_blog_blogar_status_7993db_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время модерации'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_blog_comments', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='moderation_notes',
            field=models.TextField(blank=True, verbose_name='Заметки модератора'),
        ),
    ]
