# Generated by Django 5.2.8 on 2025-12-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcomment_moderated_at_blogcomment_moderated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает модерации'), ('approved', 'Одобрен'), ('rejected', 'Отклонен'), ('spam', 'Спам'), ('deleted', 'Удален')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
