# Generated by Django 5.2.8 on 2025-12-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogcomment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, verbose_name='IP-адрес'),
        ),
    ]
