# Generated by Django 5.2.8 on 2025-12-25 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogcomment_ip_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('video', 'Видео'), ('quote', 'Цитата'), ('code', 'Код')], default='text', max_length=20)),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('caption', models.TextField(blank=True, verbose_name='Подпись')),
                ('text_content', models.TextField(blank=True, verbose_name='Текст')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='blog/blocks/%Y/%m/')),
                ('video_url', models.URLField(blank=True, verbose_name='Ссылка на видео')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='blog.blogarticle')),
            ],
            options={
                'verbose_name': 'Блок контента',
                'verbose_name_plural': 'Блоки контента',
                'ordering': ['order', 'id'],
            },
        ),
    ]
