# Generated by Django 5.2.8 on 2025-12-25 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_articlecontentblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecontentblock',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='articlecontentblock',
            name='video_url',
        ),
        migrations.AddField(
            model_name='articlecontentblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/blocks/%Y/%m/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='articlecontentblock',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='blog.blogarticle', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articlecontentblock',
            name='block_type',
            field=models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение')], default='text', max_length=20, verbose_name='Тип блока'),
        ),
        migrations.AlterField(
            model_name='articlecontentblock',
            name='text_content',
            field=models.TextField(blank=True, verbose_name='Текстовое содержимое'),
        ),
        migrations.AddIndex(
            model_name='articlecontentblock',
            index=models.Index(fields=['article', 'order'], name='blog_articl_article_100c8e_idx'),
        ),
    ]
