# Generated by Django 5.2.8 on 2025-11-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_specifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_payment_finalized',
            field=models.BooleanField(default=False, verbose_name='Оплата завершена'),
        ),
        migrations.AddField(
            model_name='order',
            name='net_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Чистая выручка (без доставки и комиссий)'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплаченная сумма'),
        ),
    ]
