# Generated by Django 5.2.7 on 2025-10-03 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_loginattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('order_created', 'Создан заказ'), ('payment_success', 'Успешная оплата'), ('order_cancelled', 'Заказ отменен'), ('telegram_sent', 'Отправлено в Telegram'), ('email_sent', 'Отправлено по email'), ('webhook_received', 'Получен webhook'), ('contact_form', 'Форма обратной связи')], max_length=20, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.order', verbose_name='Заказ'),
        ),
    ]
