# Generated by Django 5.2.8 on 2025-11-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_order_is_payment_finalized_order_net_revenue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='Россия', max_length=100, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='address',
            name='delivery_zone',
            field=models.CharField(blank=True, choices=[('central', 'Центральный'), ('far_east', 'Дальний восток'), ('siberia', 'Сибирь'), ('ural', 'Урал'), ('south', 'Юг'), ('north_west', 'Северо-Запад')], max_length=20, verbose_name='Зона доставки'),
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_fragile',
            field=models.BooleanField(default=False, verbose_name='Хрупкий товар'),
        ),
        migrations.AddField(
            model_name='product',
            name='requires_special_delivery',
            field=models.BooleanField(default=False, verbose_name='Требует спецдоставки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, max_length=50, verbose_name='Габариты (Д×Ш×В см)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=8, verbose_name='Вес (кг)'),
        ),
    ]
