# Generated by Django 5.2.7 on 2025-10-04 13:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_notificationlog_notification_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery',
            field=models.DateField(blank=True, null=True, verbose_name='Примерная дата доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='Служба доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_changed_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 10, 4, 13, 15, 4, 839239, tzinfo=datetime.timezone.utc), verbose_name='Время изменения статуса'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Трек-номер'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('processing', 'В обработке'), ('assembling', 'Собирается'), ('ready_for_shipping', 'Готов к отправке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('refunded', 'Возврат')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='OrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('processing', 'В обработке'), ('assembling', 'Собирается'), ('ready_for_shipping', 'Готов к отправке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('refunded', 'Возврат')], max_length=20, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('processing', 'В обработке'), ('assembling', 'Собирается'), ('ready_for_shipping', 'Готов к отправке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('refunded', 'Возврат')], max_length=20, verbose_name='Новый статус')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Время изменения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Лог статуса заказа',
                'verbose_name_plural': 'Логи статусов заказов',
                'ordering': ['-changed_at'],
            },
        ),
    ]
