# Generated by Django 5.2.6 on 2025-10-01 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_customer_address_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_created', 'Создан заказ'), ('payment_success', 'Успешная оплата'), ('order_cancelled', 'Заказ отменен'), ('telegram_sent', 'Отправлено в Telegram'), ('email_sent', 'Отправлено по email'), ('webhook_received', 'Получен webhook')], max_length=20, verbose_name='Тип уведомления')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('sent_to', models.CharField(blank=True, max_length=200, verbose_name='Получатель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('success', models.BooleanField(default=True, verbose_name='Успешно')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Лог уведомлений',
                'verbose_name_plural': 'Логи уведомлений',
                'ordering': ['-created_at'],
            },
        ),
    ]
