# Generated by Django 5.2.7 on 2025-10-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_estimated_delivery_order_shipping_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_changed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения статуса'),
        ),
    ]
