# Generated by Django 5.2.8 on 2025-11-27 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userprofile_account_type_userprofile_bank_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('slug', models.CharField(choices=[('service_electrical', 'Электромонтажные работы'), ('service_design', 'Проектирование систем'), ('service_software', 'Разработка ПО и SCADA'), ('service_equipment', 'Поставка оборудования'), ('service_support', 'Техническая поддержка'), ('service_maintenance', 'Сервисное обслуживание')], max_length=50, unique=True, verbose_name='Идентификатор')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета-описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок секции')),
                ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('section_type', models.CharField(choices=[('hero', 'Hero секция'), ('text_image', 'Текст + изображение'), ('features', 'Особенности'), ('services', 'Услуги'), ('steps', 'Этапы работы'), ('gallery', 'Галерея'), ('cta', 'Призыв к действию'), ('faq', 'Частые вопросы')], max_length=20, verbose_name='Тип секции')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('background_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет фона')),
                ('text_color', models.CharField(default='#333333', max_length=7, verbose_name='Цвет текста')),
                ('extra_css', models.TextField(blank=True, verbose_name='Дополнительные CSS стили')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Секция страницы',
                'verbose_name_plural': 'Секции страниц',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Иконка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='main.pagesection', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Особенность',
                'verbose_name_plural': 'Особенности',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='page_media/%Y/%m/%d/', verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], max_length=10, verbose_name='Тип файла')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt текст')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='main.pagesection', verbose_name='Секция')),
            ],
            options={
                'verbose_name': 'Медиа файл',
                'verbose_name_plural': 'Медиа файлы',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
