# Generated by Django 5.2.8 on 2025-11-27 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_page_pagesection_sectionfeature_sectionmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-адрес')),
                ('page_type', models.CharField(choices=[('service', 'Страница услуги'), ('info', 'Информационная страница'), ('custom', 'Пользовательская страница')], default='service', max_length=20, verbose_name='Тип страницы')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета-описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('show_in_navigation', models.BooleanField(default=True, verbose_name='Показывать в навигации')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO заголовок')),
                ('seo_keywords', models.TextField(blank=True, verbose_name='SEO ключевые слова')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Динамическая страница',
                'verbose_name_plural': 'Динамические страницы',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='pagesection',
            name='custom_classes',
            field=models.CharField(blank=True, max_length=200, verbose_name='CSS классы'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='section_type',
            field=models.CharField(choices=[('hero', 'Hero секция'), ('text_image', 'Текст + изображение'), ('features', 'Особенности'), ('services', 'Услуги'), ('steps', 'Этапы работы'), ('gallery', 'Галерея'), ('cta', 'Призыв к действию'), ('faq', 'Частые вопросы'), ('custom', 'Пользовательская секция')], max_length=20, verbose_name='Тип секции'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='main.dynamicpage', verbose_name='Страница'),
        ),
    ]
