# Generated by Django 5.2.8 on 2025-11-27 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_dynamicpage_pagesection_custom_classes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-адрес')),
                ('page_type', models.CharField(choices=[('main_service', 'Основная услуга'), ('sub_service', 'Подуслуга'), ('instruction', 'Инструкция')], default='main_service', max_length=20, verbose_name='Тип страницы')),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок героя')),
                ('hero_subtitle', models.TextField(blank=True, verbose_name='Подзаголовок героя')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='service_heroes/', verbose_name='Изображение героя')),
                ('content', models.TextField(blank=True, verbose_name='Основной контент')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Особенности')),
                ('meta_description', models.TextField(blank=True, verbose_name='Мета-описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('show_in_navigation', models.BooleanField(default=True, verbose_name='Показывать в навигации')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.servicepage', verbose_name='Родительская страница')),
            ],
            options={
                'verbose_name': 'Страница услуги',
                'verbose_name_plural': 'Страницы услуг',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.RemoveField(
            model_name='pagesection',
            name='page',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.RemoveField(
            model_name='sectionfeature',
            name='section',
        ),
        migrations.RemoveField(
            model_name='sectionmedia',
            name='section',
        ),
        migrations.DeleteModel(
            name='DynamicPage',
        ),
        migrations.DeleteModel(
            name='SectionFeature',
        ),
        migrations.DeleteModel(
            name='PageSection',
        ),
        migrations.DeleteModel(
            name='SectionMedia',
        ),
    ]
