# Generated by Django 5.2.6 on 2025-10-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Банковская карта (прямая)'), ('yookassa_card', 'Карта через ЮКассу'), ('sbp', 'СБП (Система быстрых платежей)'), ('invoice', 'По счету')], default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
