# Generated by Django 5.2.8 on 2025-11-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_servicepage_remove_pagesection_page_delete_page_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicepage',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Дополнительная страница услуги', 'verbose_name_plural': 'Дополнительные страницы услуг'},
        ),
        migrations.AddField(
            model_name='servicepage',
            name='static_service',
            field=models.CharField(blank=True, choices=[('design', 'Проектирование систем'), ('electrical', 'Электромонтажные работы'), ('software', 'Разработка ПО и SCADA'), ('equipment', 'Поставка оборудования'), ('support', 'Техническая поддержка'), ('maintenance', 'Сервисное обслуживание')], max_length=20, verbose_name='Привязать к статической странице'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='features',
            field=models.JSONField(blank=True, default=dict, verbose_name='Особенности'),
        ),
    ]
