# Generated by Django 5.2.8 on 2025-11-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_servicepage_options_servicepage_static_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='features',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='features_text',
            field=models.TextField(blank=True, help_text='Каждая особенность с новой строки. Формат: Заголовок|Описание (разделитель - вертикальная черта)', verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='static_service',
            field=models.CharField(blank=True, choices=[('', '--- Не привязано ---'), ('design', 'Проектирование систем'), ('electrical', 'Электромонтажные работы'), ('software', 'Разработка ПО и SCADA'), ('equipment', 'Поставка оборудования'), ('support', 'Техническая поддержка'), ('maintenance', 'Сервисное обслуживание')], default='', max_length=20, verbose_name='Привязать к статической странице'),
        ),
    ]
