# Generated by Django 5.2.6 on 2025-10-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Банковская карта'), ('invoice', 'По счету')], default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
