# Generated by Django 5.2.8 on 2025-12-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_servicepage_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price_without_vat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Рассчитывается автоматически', max_digits=10, verbose_name='Цена без НДС'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_without_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма без НДС'),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма НДС'),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Ставка НДС (%)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_without_vat',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Рассчитывается автоматически', max_digits=10, verbose_name='Цена без НДС'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма НДС'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Ставка НДС (%)'),
        ),
    ]
