# Generated by Django 5.2.8 on 2025-12-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_order_price_without_vat_order_total_without_vat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Ставка НДС (%)'),
        ),
    ]
