# Generated by Django 5.2.6 on 2025-10-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cardlink_transaction_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID транзакции Cardlink'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_system',
            field=models.CharField(choices=[('yookassa', 'ЮКасса'), ('cardlink', 'Cardlink')], default='yookassa', max_length=20, verbose_name='Платежная система'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Банковская карта'), ('invoice', 'По счету'), ('cardlink', 'Cardlink')], default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
