# Generated by Django 5.2.8 on 2025-12-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_product_vat_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cardlink_transaction_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_system',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('invoice', 'По счету')], default='card', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
