# Generated by Django 5.2.6 on 2025-10-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_supportticket_supportattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='cookies_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='javascript_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
