# Generated by Django 5.2.8 on 2025-12-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_order_cardlink_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_inn',
            field=models.CharField(blank=True, help_text='Для юридических лиц', max_length=12, null=True, verbose_name='ИНН покупателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_kpp',
            field=models.CharField(blank=True, help_text='Для юридических лиц', max_length=9, null=True, verbose_name='КПП покупателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_date',
            field=models.DateField(blank=True, help_text='Дата выставления счета', null=True, verbose_name='Дата счета'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Автоматически генерируется при создании счета', max_length=50, null=True, unique=True, verbose_name='Номер счета'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_sent',
            field=models.BooleanField(default=False, help_text='Счет отправлен на email покупателя', verbose_name='Счет отправлен'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отправки счета'),
        ),
    ]
