# Generated by Django 5.2.6 on 2025-11-10 07:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_supportticket_cookies_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin2FA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='2FA включена')),
                ('secret_key', models.CharField(max_length=32, verbose_name='Секретный ключ')),
                ('backup_codes', models.JSONField(default=list, verbose_name='Резервные коды')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': '2FA администратора',
                'verbose_name_plural': '2FA администраторов',
            },
        ),
        migrations.CreateModel(
            name='CSPViolationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_uri', models.URLField(verbose_name='URI документа')),
                ('violated_directive', models.CharField(max_length=100, verbose_name='Нарушенная директива')),
                ('effective_directive', models.CharField(max_length=100, verbose_name='Эффективная директива')),
                ('original_policy', models.TextField(verbose_name='Оригинальная политика')),
                ('blocked_uri', models.URLField(blank=True, null=True, verbose_name='Заблокированный URI')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='Исходный файл')),
                ('line_number', models.IntegerField(blank=True, null=True, verbose_name='Номер строки')),
                ('column_number', models.IntegerField(blank=True, null=True, verbose_name='Номер колонки')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отчет CSP',
                'verbose_name_plural': 'Отчеты CSP',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FraudDetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('severity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], max_length=10, verbose_name='Серьезность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('reasons', models.JSONField(default=list, verbose_name='Причины')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Обнаружено')),
                ('resolved', models.BooleanField(default=False, verbose_name='Решено')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Решено в')),
            ],
            options={
                'verbose_name': 'Лог мошенничества',
                'verbose_name_plural': 'Логи мошенничества',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('payment_created', 'Платеж создан'), ('payment_succeeded', 'Платеж успешен'), ('payment_failed', 'Платеж не удался'), ('refund_created', 'Возврат создан'), ('refund_succeeded', 'Возврат успешен'), ('webhook_received', 'Webhook получен'), ('webhook_processed', 'Webhook обработан'), ('amount_mismatch', 'Несоответствие суммы'), ('duplicate_payment', 'Дублирующий платеж')], max_length=20, verbose_name='Действие')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('details', models.JSONField(default=dict, verbose_name='Детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Аудит платежа',
                'verbose_name_plural': 'Аудит платежей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateLimitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, verbose_name='Ключ ограничения')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('attempts', models.IntegerField(default=1, verbose_name='Попытки')),
                ('window_start', models.DateTimeField(verbose_name='Начало окна')),
                ('window_end', models.DateTimeField(verbose_name='Конец окна')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='Заблокировано до')),
            ],
            options={
                'verbose_name': 'Лог ограничения запросов',
                'verbose_name_plural': 'Логи ограничения запросов',
            },
        ),
        migrations.AlterModelOptions(
            name='securitylog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Лог безопасности', 'verbose_name_plural': 'Логи безопасности'},
        ),
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='fraud_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Оценка мошенничества'),
        ),
        migrations.AddField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес создания'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AddField(
            model_name='orderstatuslog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_restock',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее пополнение'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='details',
            field=models.JSONField(default=dict, verbose_name='Детали'),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='low', max_length=10, verbose_name='Уровень риска'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='Email подтвержден'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_security_notification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата смены пароля'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_token_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='notification_type',
            field=models.CharField(choices=[('order_created', 'Создан заказ'), ('payment_success', 'Успешная оплата'), ('order_cancelled', 'Заказ отменен'), ('telegram_sent', 'Отправлено в Telegram'), ('email_sent', 'Отправлено по email'), ('webhook_received', 'Получен webhook'), ('contact_form', 'Форма обратной связи'), ('security_alert', 'Предупреждение безопасности'), ('fraud_alert', 'Предупреждение мошенничества')], max_length=20, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('processing', 'В обработке'), ('assembling', 'Собирается'), ('ready_for_shipping', 'Готов к отправке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('refunded', 'Возврат'), ('disputed', 'Оспаривается')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='new_status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('processing', 'В обработке'), ('assembling', 'Собирается'), ('ready_for_shipping', 'Готов к отправке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('refunded', 'Возврат'), ('disputed', 'Оспаривается')], max_length=20, verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='orderstatuslog',
            name='old_status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('processing', 'В обработке'), ('assembling', 'Собирается'), ('ready_for_shipping', 'Готов к отправке'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('refunded', 'Возврат'), ('disputed', 'Оспаривается')], max_length=20, verbose_name='Предыдущий статус'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Вход в систему'), ('login_failed', 'Неудачная попытка входа'), ('logout', 'Выход из системы'), ('password_change', 'Смена пароля'), ('password_reset_request', 'Запрос сброса пароля'), ('password_reset_success', 'Успешный сброс пароля'), ('profile_update', 'Обновление профиля'), ('register', 'Регистрация'), ('register_failed', 'Неудачная регистрация'), ('email_verification', 'Подтверждение email'), ('payment_attempt', 'Попытка оплаты'), ('payment_success', 'Успешная оплата'), ('payment_failed', 'Неудачная оплата'), ('admin_access', 'Доступ к админке'), ('suspicious_activity', 'Подозрительная активность'), ('fraud_attempt', 'Попытка мошенничества'), ('webhook_received', 'Получен webhook'), ('api_access', 'Доступ к API')], max_length=50, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP-адрес'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='success',
            field=models.BooleanField(default=True, verbose_name='Успешно'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['ip_address', 'timestamp'], name='main_logina_ip_addr_7d1a44_idx'),
        ),
        migrations.AddIndex(
            model_name='loginattempt',
            index=models.Index(fields=['username', 'timestamp'], name='main_logina_usernam_28215e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='main_order_user_id_c1b0f1_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='main_order_status_86232c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method', 'created_at'], name='main_order_payment_468dee_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresettoken',
            index=models.Index(fields=['token', 'expires_at'], name='main_passwo_token_78ca8d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', 'category'], name='main_produc_is_acti_05a6d9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price', 'is_active'], name='main_produc_price_80d4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['user', 'timestamp'], name='main_securi_user_id_624543_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='main_securi_ip_addr_197ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['action', 'timestamp'], name='main_securi_action_72ff24_idx'),
        ),
        migrations.AddField(
            model_name='admin2fa',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frauddetectionlog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='frauddetectionlog',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_fraud_cases', to=settings.AUTH_USER_MODEL, verbose_name='Решено кем'),
        ),
        migrations.AddField(
            model_name='frauddetectionlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order', verbose_name='Заказ'),
        ),
        migrations.AddField(
            model_name='paymentauditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='ratelimitlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddIndex(
            model_name='paymentauditlog',
            index=models.Index(fields=['order', 'created_at'], name='main_paymen_order_i_f50d80_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentauditlog',
            index=models.Index(fields=['user', 'created_at'], name='main_paymen_user_id_be8e21_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitlog',
            index=models.Index(fields=['key', 'window_start'], name='main_rateli_key_aac1be_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimitlog',
            index=models.Index(fields=['ip_address', 'window_start'], name='main_rateli_ip_addr_6ae6e9_idx'),
        ),
    ]
