# Generated by Django 5.2.8 on 2025-12-17 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_product_options_product_seo_description_and_more'),
    ]

    operations = [
    ]
