# Generated by Django 5.2.8 on 2025-12-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20251217_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='main_produc_article_a7a5a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='main_produc_slug_354b31_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=50, verbose_name='Артикул'),
        ),
    ]
