# Generated by Django 5.2.8 on 2025-12-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Автоматически генерируется', max_length=160, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_keywords',
            field=models.TextField(blank=True, help_text='Автоматически генерируется', verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='product',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Автоматически генерируется', max_length=200, verbose_name='SEO Title'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='Автоматически генерируется из названия', max_length=200, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, editable=False, help_text='Автоматически генерируется при создании', max_length=15, unique=True, verbose_name='Артикул'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['article'], name='main_produc_article_a7a5a0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='main_produc_slug_354b31_idx'),
        ),
    ]
