# Generated by Django 5.2.8 on 2025-12-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_product_options_product_seo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylog',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, verbose_name='IP-адрес'),
        ),
    ]
