# Generated by Django 5.2.8 on 2025-12-23 13:03

import main.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_securitylog_ip_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_large',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='avatars/large/%Y/%m/', verbose_name='Большой аватар (200x200)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_medium',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='avatars/medium/%Y/%m/', verbose_name='Средний аватар (100x100)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_small',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='avatars/small/%Y/%m/', verbose_name='Маленький аватар (50x50)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Активен ли профиль', verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Верифицированный профиль'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_profile_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Последнее обновление профиля'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_mode',
            field=models.CharField(choices=[('public', 'Публичный профиль'), ('private', 'Приватный профиль'), ('hidden', 'Скрытый (только админы)')], default='public', max_length=10, verbose_name='Режим приватности'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='private_notes',
            field=models.TextField(blank=True, help_text='Только для вашего просмотра', verbose_name='Личные заметки'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_background',
            field=models.ImageField(blank=True, null=True, upload_to='profile_backgrounds/%Y/%m/', validators=[main.validators.validate_profile_background], verbose_name='Фон профиля'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_meta_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Meta Description профиля'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Meta Title профиля'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_slug',
            field=models.SlugField(blank=True, help_text='Используется для публичных ссылок на профиль', max_length=100, null=True, unique=True, verbose_name='URL профиля'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_tags',
            field=models.JSONField(blank=True, default=list, help_text='Теги назначаются администратором', verbose_name='Теги профиля'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_theme',
            field=models.CharField(default='default', help_text='Цветовая тема профиля', max_length=50, verbose_name='Тема профиля'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотры профиля'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_bio',
            field=models.TextField(blank=True, help_text='Будет видна другим пользователям', max_length=1000, verbose_name='Публичная биография'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_links',
            field=models.JSONField(blank=True, default=list, help_text='Список ссылок в формате [{"name": "GitHub", "url": "https://..."}]', verbose_name='Публичные ссылки'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_skills',
            field=models.CharField(blank=True, help_text='Навыки через запятую', max_length=500, verbose_name='Публичные навыки'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_recent_activity',
            field=models.BooleanField(default=True, verbose_name='Показывать активность'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='show_statistics',
            field=models.BooleanField(default=True, verbose_name='Показывать статистику'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_badge',
            field=models.CharField(blank=True, max_length=50, verbose_name='Бейдж верификации'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', validators=[main.validators.validate_avatar], verbose_name='Аватар'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['profile_slug'], name='main_userpr_profile_02cefe_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['privacy_mode', 'is_active'], name='main_userpr_privacy_fb6a6e_idx'),
        ),
    ]
