# Generated by Django 5.2.8 on 2025-12-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_userprofile_avatar_large_userprofile_avatar_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_visibility',
            field=models.CharField(choices=[('public', 'Публично'), ('private', 'Только мне'), ('friends', 'Друзьям'), ('registered', 'Зарегистрированным')], default='public', max_length=20, verbose_name='Видимость активности'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company_visibility',
            field=models.CharField(choices=[('public', 'Публично'), ('private', 'Только мне'), ('friends', 'Друзьям'), ('registered', 'Зарегистрированным')], default='public', max_length=20, verbose_name='Видимость компании'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_visibility',
            field=models.CharField(choices=[('public', 'Публично'), ('private', 'Только мне'), ('friends', 'Друзьям'), ('registered', 'Зарегистрированным')], default='private', max_length=20, verbose_name='Видимость email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_visibility',
            field=models.CharField(choices=[('public', 'Публично'), ('private', 'Только мне'), ('friends', 'Друзьям'), ('registered', 'Зарегистрированным')], default='private', max_length=20, verbose_name='Видимость телефона'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='position_visibility',
            field=models.CharField(choices=[('public', 'Публично'), ('private', 'Только мне'), ('friends', 'Друзьям'), ('registered', 'Зарегистрированным')], default='public', max_length=20, verbose_name='Видимость должности'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills_visibility',
            field=models.CharField(choices=[('public', 'Публично'), ('private', 'Только мне'), ('friends', 'Друзьям'), ('registered', 'Зарегистрированным')], default='public', max_length=20, verbose_name='Видимость навыков'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='privacy_mode',
            field=models.CharField(choices=[('public', 'Публично'), ('private', 'Только мне'), ('friends', 'Друзьям'), ('registered', 'Зарегистрированным')], default='public', max_length=10, verbose_name='Режим приватности'),
        ),
    ]
