# Generated by Django 5.2.8 on 2025-12-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_userprofile_activity_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='Например: ABB, Schneider Electric, Siemens', max_length=100, verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='Формат: Длина×Ширина×Высота в см. Пример: 10×20×5', max_length=50, verbose_name='Габариты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, help_text='Например: пластик, сталь, алюминий, комбинированный', max_length=100, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, default=dict, help_text="Дополнительные характеристики в формате JSON. Пример: {'Мощность': '100W', 'Напряжение': '220V'}", verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty',
            field=models.IntegerField(default=12, help_text='Срок гарантии в месяцах. Стандартно 12 месяцев', verbose_name='Гарантия (мес)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Вес в килограммах. Пример: 2.5', max_digits=8, null=True, verbose_name='Вес'),
        ),
    ]
