# Generated by Django 5.2.8 on 2025-12-30 08:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_product_brand_alter_product_dimensions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=22.0, max_digits=5, verbose_name='Ставка НДС (%)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('22.00'), max_digits=5, verbose_name='Ставка НДС (%)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('22.00'), max_digits=5, verbose_name='Ставка НДС (%)'),
        ),
    ]
