# Generated by Django 5.2.8 on 2026-01-22 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_order_vat_rate_alter_orderitem_vat_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('created', 'Создан'), ('sent', 'Отправлен'), ('paid', 'Оплачен'), ('expired', 'Просрочен'), ('cancelled', 'Отменен')], default='created', max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_inn', models.CharField(blank=True, max_length=12, null=True)),
                ('customer_kpp', models.CharField(blank=True, max_length=9, null=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('items_json', models.JSONField(default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100)),
                ('payment_comment', models.TextField(blank=True)),
                ('excel_created', models.BooleanField(default=False)),
                ('excel_sent_to_tg', models.BooleanField(default=False)),
                ('excel_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_doc', to='main.order')),
            ],
            options={
                'ordering': ['-invoice_date', '-created_at'],
                'indexes': [models.Index(fields=['invoice_number'], name='main_invoic_invoice_0a8ac4_idx'), models.Index(fields=['status'], name='main_invoic_status_1c3a54_idx'), models.Index(fields=['invoice_date'], name='main_invoic_invoice_d66b1d_idx')],
            },
        ),
    ]
