# Generated by Django 5.2.8 on 2026-01-22 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Номер счета')),
                ('invoice_date', models.DateField(verbose_name='Дата счета')),
                ('due_date', models.DateField(verbose_name='Срок оплаты')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Покупатель')),
                ('customer_inn', models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН покупателя')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email покупателя')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон покупателя')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма счета')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма НДС')),
                ('amount_without_vat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма без НДС')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('sent', 'Отправлен'), ('paid', 'Оплачен'), ('overdue', 'Просрочен'), ('cancelled', 'Отменен')], default='created', max_length=20, verbose_name='Статус счета')),
                ('email_sent', models.BooleanField(default=False, verbose_name='Email отправлен')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email отправлен в')),
                ('telegram_sent', models.BooleanField(default=False, verbose_name='Telegram отправлен')),
                ('telegram_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Telegram отправлен в')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('payment_details', models.JSONField(blank=True, default=dict, verbose_name='Детали оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_registry', to='main.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Реестр счетов',
                'verbose_name_plural': 'Реестр счетов',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.AddIndex(
            model_name='invoiceregistry',
            index=models.Index(fields=['invoice_number'], name='main_invoic_invoice_94deff_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceregistry',
            index=models.Index(fields=['status', 'due_date'], name='main_invoic_status_0d9e72_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceregistry',
            index=models.Index(fields=['customer_name', 'invoice_date'], name='main_invoic_custome_28fde2_idx'),
        ),
    ]
