# Generated by Django 5.2.8 on 2026-01-27 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_invoiceregistry_delete_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Автоматически генерируется из названия', max_length=200, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO Title')),
                ('seo_description', models.TextField(blank=True, max_length=160, verbose_name='SEO Description')),
                ('seo_keywords', models.TextField(blank=True, verbose_name='SEO Keywords')),
                ('show_in_menu', models.BooleanField(default=True, verbose_name='Показывать в меню')),
                ('product_count', models.IntegerField(default=0, editable=False, verbose_name='Количество товаров')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='main_produc_is_acti_99184a_idx',
            old_name='main_produc_is_acti_05a6d9_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='main.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='main.category', verbose_name='Категория'),
        ),
    ]
