# Generated by Django 5.2.8 on 2026-01-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=100, verbose_name='Категория'),
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='main_produc_is_acti_05a6d9_idx',
            old_name='main_produc_is_acti_99184a_idx',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
