# Generated by Django 5.2.8 on 2026-01-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RUB', 'Российский рубль'), ('USD', 'Доллар США'), ('EUR', 'Евро')], max_length=3, unique=True, verbose_name='Валюта')),
                ('rate_to_rub', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс к рублю')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный курс')),
            ],
            options={
                'verbose_name': 'Курс валюты',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ['currency'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('RUB', '₽ Рубль'), ('USD', '$ Доллар США'), ('EUR', '€ Евро')], default='RUB', help_text='Валюта, в которой указана цена товара', max_length=3, verbose_name='Валюта цены'),
        ),
        migrations.AddField(
            model_name='product',
            name='last_rate_update',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Последнее обновление курса'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_in_rub',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Цена в рублях'),
        ),
    ]
