# Generated by Django 5.2.8 on 2026-01-30 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_currencyrate_product_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_in_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена в рублях'),
        ),
    ]
