# Generated by Django 5.2.8 on 2026-01-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_product_price_in_rub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='last_rate_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление курса'),
        ),
    ]
