# Generated by Django 5.2.8 on 2026-02-02 09:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_product_last_rate_update'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email для связи')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('request_type', models.CharField(choices=[('access', 'Запрос о предоставлении сведений об обработке ПД'), ('correction', 'Требование об уточнении персональных данных'), ('blocking', 'Требование о блокировании персональных данных'), ('destruction', 'Требование об уничтожении персональных данных'), ('withdraw_consent', 'Отзыв согласия на обработку персональных данных'), ('objection', 'Возражение против обработки персональных данных'), ('complaint', 'Жалоба на обработку персональных данных')], max_length=50, verbose_name='Тип запроса')),
                ('description', models.TextField(verbose_name='Описание запроса')),
                ('preferred_response', models.CharField(choices=[('email', 'Email'), ('phone', 'Телефон'), ('post', 'Почта')], default='email', max_length=20, verbose_name='Предпочтительный способ ответа')),
                ('verification_document', models.FileField(blank=True, null=True, upload_to='privacy_requests/verification/%Y/%m/', verbose_name='Документ для верификации')),
                ('status', models.CharField(choices=[('received', 'Получен'), ('in_progress', 'В обработке'), ('waiting_verification', 'Ожидает верификации'), ('completed', 'Выполнен'), ('rejected', 'Отклонен'), ('cancelled', 'Отменен')], default='received', max_length=50, verbose_name='Статус')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения')),
                ('response_text', models.TextField(blank=True, verbose_name='Текст ответа')),
                ('response_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки ответа')),
                ('response_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Телефон'), ('post', 'Почта')], max_length=20, verbose_name='Способ отправки ответа')),
                ('notes', models.TextField(blank=True, verbose_name='Внутренние заметки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='privacy_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запрос по персональным данным',
                'verbose_name_plural': 'Запросы по персональным данным',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'created_at'], name='main_privac_email_41f5cc_idx'), models.Index(fields=['status', 'created_at'], name='main_privac_status_baa441_idx')],
            },
        ),
    ]
