# Generated by Django 5.2.8 on 2026-02-02 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_privacyrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProtectionOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('appointment_date', models.DateField(verbose_name='Дата назначения')),
                ('appointment_order', models.CharField(max_length=100, verbose_name='Номер приказа')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действующий')),
            ],
            options={
                'verbose_name': 'Ответственный за ПД',
                'verbose_name_plural': 'Ответственные за ПД',
            },
        ),
        migrations.CreateModel(
            name='ProcessingRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование обработки')),
                ('purpose', models.TextField(verbose_name='Цель обработки')),
                ('categories', models.TextField(verbose_name='Категории субъектов ПД')),
                ('data_categories', models.TextField(verbose_name='Категории ПД')),
                ('legal_basis', models.TextField(verbose_name='Правовое основание')),
                ('processing_type', models.CharField(choices=[('automated', 'Автоматизированная'), ('manual', 'Неавтоматизированная'), ('mixed', 'Смешанная')], max_length=20, verbose_name='Тип обработки')),
                ('storage_type', models.CharField(choices=[('electronic', 'Электронный'), ('paper', 'Бумажный'), ('mixed', 'Смешанный')], max_length=20, verbose_name='Форма хранения')),
                ('retention_period', models.CharField(max_length=100, verbose_name='Срок хранения')),
                ('destruction_procedure', models.TextField(verbose_name='Порядок уничтожения')),
                ('security_measures', models.TextField(verbose_name='Применяемые меры защиты')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата внесения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Запись реестра обработки ПД',
                'verbose_name_plural': 'Реестр обработки ПД',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='privacyrequest',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок рассмотрения'),
        ),
        migrations.AddField(
            model_name='privacyrequest',
            name='incoming_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Входящий номер'),
        ),
        migrations.CreateModel(
            name='PrivacyRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(default=dict)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.privacyrequest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
