# Generated by Django 5.2.8 on 2026-02-02 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_dataprotectionofficer_processingregister_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('registration', 'Согласие при регистрации'), ('newsletter', 'Согласие на рассылку'), ('marketing', 'Согласие на маркетинговые коммуникации'), ('cookies', 'Согласие на использование cookies'), ('analytics', 'Согласие на аналитику')], max_length=50, verbose_name='Тип согласия')),
                ('version', models.CharField(max_length=20, verbose_name='Версия согласия')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Действует')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отзыва')),
                ('document_url', models.URLField(blank=True, verbose_name='Ссылка на документ')),
                ('purpose', models.TextField(verbose_name='Цель обработки')),
                ('data_categories', models.JSONField(default=list, verbose_name='Категории данных')),
                ('third_parties', models.JSONField(default=list, verbose_name='Третьи стороны')),
                ('storage_period', models.CharField(max_length=100, verbose_name='Срок хранения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Согласие на обработку ПД',
                'verbose_name_plural': 'Согласия на обработку ПД',
            },
        ),
        migrations.CreateModel(
            name='PrivacyConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Действие')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адрес')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('details', models.JSONField(default=dict, verbose_name='Детали')),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.privacyconsent', verbose_name='Согласие')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог согласия',
                'verbose_name_plural': 'Логи согласий',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='privacyconsent',
            index=models.Index(fields=['user', 'consent_type', 'is_active'], name='main_privac_user_id_1c26f3_idx'),
        ),
        migrations.AddIndex(
            model_name='privacyconsent',
            index=models.Index(fields=['granted_at', 'is_active'], name='main_privac_granted_c84c0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='privacyconsent',
            unique_together={('user', 'consent_type', 'version')},
        ),
    ]
