# Generated by Django 5.2.8 on 2026-02-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_privacyconsent_privacyconsentlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='detailed_consent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подписания подробного согласия'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_detailed_consent',
            field=models.BooleanField(default=False, verbose_name='Имеет подробное согласие'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_privacy_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление настроек приватности'),
        ),
    ]
