# Generated by Django 5.2.8 on 2026-04-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_category_created_at_category_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_legal',
            field=models.BooleanField(default=False, verbose_name='Юридическое лицо'),
        ),
        migrations.AddField(
            model_name='address',
            name='legal_address',
            field=models.TextField(blank=True, verbose_name='Юридический адрес'),
        ),
    ]
