# Generated by Django 5.2.8 on 2026-04-03 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_address_is_legal_address_legal_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название прайс-листа')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-листы',
            },
        ),
        migrations.CreateModel(
            name='ClientDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percent', 'Процентная'), ('fixed', 'Фиксированная')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка (%)')),
                ('valid_from', models.DateField(auto_now_add=True)),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, verbose_name='Причина скидки')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Макс. сумма скидки')),
                ('applicable_categories', models.ManyToManyField(blank=True, to='main.category', verbose_name='Только для категорий')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_discounts', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Скидка клиента',
                'verbose_name_plural': 'Скидки клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientPriceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название договора')),
                ('contract_number', models.CharField(max_length=50)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('contract_file', models.FileField(blank=True, upload_to='contracts/%Y/%m/')),
                ('special_prices', models.JSONField(blank=True, default=dict, verbose_name='Спеццены {product_id: price}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommercialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('valid_until', models.DateField(verbose_name='Действительно до')),
                ('items', models.JSONField(default=list, verbose_name='Позиции')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('approved', 'Согласован'), ('rejected', 'Отклонен'), ('converted', 'Преобразован в заказ'), ('expired', 'Истек')], default='draft', max_length=20)),
                ('pdf_file', models.FileField(blank=True, upload_to='offers/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
                ('converted_to_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.order')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Коммерческое предложение',
                'verbose_name_plural': 'Коммерческие предложения',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('contract_type', models.CharField(choices=[('supply', 'Договор поставки'), ('service', 'Договор оказания услуг'), ('nda', 'Соглашение о конфиденциальности'), ('framework', 'Рамочный договор')], max_length=20)),
                ('signed_at', models.DateField()),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('signed_file', models.FileField(upload_to='contracts/signed/%Y/%m/', verbose_name='Подписанный договор')),
                ('scan_file', models.FileField(blank=True, upload_to='contracts/scans/%Y/%m/')),
                ('auto_renew', models.BooleanField(default=False)),
                ('renewal_notice_days', models.IntegerField(default=30, verbose_name='Дней до уведомления')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('signed', 'Подписан'), ('expired', 'Истек'), ('terminated', 'Расторгнут')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('min_quantity', models.PositiveIntegerField(default=1, verbose_name='Мин. количество')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.pricelist')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
            options={
                'unique_together': {('price_list', 'product', 'min_quantity')},
            },
        ),
    ]
