# Generated by Django 5.2.8 on 2026-04-08 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_order_discount_amount_order_discount_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Компания')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('task_type', models.CharField(choices=[('automation', 'Автоматизация технологических процессов'), ('electrical', 'Электромонтажные работы'), ('software', 'Разработка ПО/SCADA'), ('equipment', 'Поставка оборудования'), ('maintenance', 'Сервисное обслуживание'), ('turnkey', 'Проект под ключ'), ('other', 'Другое')], max_length=20, verbose_name='Тип задачи')),
                ('title', models.CharField(max_length=300, verbose_name='Название проекта')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочно')], default='medium', max_length=10, verbose_name='Приоритет')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Желаемый срок')),
                ('budget', models.CharField(blank=True, max_length=100, verbose_name='Бюджет (приблизительно)')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('requirements', models.TextField(blank=True, help_text='Оборудование, протоколы, условия эксплуатации', verbose_name='Технические требования')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='Вложения')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('processing', 'В обработке'), ('quoted', 'КП отправлено'), ('approved', 'Согласовано'), ('completed', 'Выполнено'), ('rejected', 'Отклонено')], default='new', max_length=20, verbose_name='Статус')),
                ('draft_data', models.JSONField(blank=True, default=dict, verbose_name='Черновик')),
                ('is_draft', models.BooleanField(default=True, verbose_name='Черновик')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Ключ сессии')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Техническое задание',
                'verbose_name_plural': 'Технические задания',
                'ordering': ['-created_at'],
            },
        ),
    ]
