# Generated by Django 5.2.8 on 2026-04-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_technicaltask'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicaltask',
            name='admin_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий администратора'),
        ),
    ]
